# dev 환경
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: "jdbc:mysql://market.csah5yoduwry.ap-northeast-2.rds.amazonaws.com:3306/market?autoReconnect=true&characterEncoding=utf8&serverTimezone=Asia/Seoul"
    username: market
    password: market12
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true