spring:
  profiles:
    active: dev

  jpa:
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: web.common.strategy.UpperCaseNamingStrategy
    show-sql: true

  security:
    user:
      password: 1111

server:
  port: 8081