spring:
  profiles:
    include: auth, datasource

  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: validate
      naming:
        physical-strategy: web.common.strategy.UpperCaseNamingStrategy
    show-sql: true

  sql:
    init:
      mode: always

  flyway:
    baseline-on-migrate: true
    enabled: true
