spring:
  profiles:
    include: auth, datasource

  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: web.common.strategy.UpperCaseNamingStrategy
    show-sql: true
    defer-datasource-initialization: true

  sql:
    init:
      mode: always
