# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a package using Gradle and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#Publishing-using-gradle

name: Gradle Package

on:
  push:
    branches: [ develop, test ]

jobs:
  build: 
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true
          token: ${{ secrets.GIT_TOKEN }}

      - name: Build
        run: ./gradlew clean build -x test
      
      - name: module-web
        uses: appleboy/scp-action@master
        with:
          username: ec2-user
          host: ${{ secrets.HOST }}
          key: ${{ secrets.RSA_PRIVATE_KEY }}
          source: "./module-web/build/libs/*.jar"
          target: "/home/ec2-user/market-everyone/"
      
      - name: module-admin
        uses: appleboy/scp-action@master
        with:
          username: ec2-user
          host: ${{ secrets.HOST }}
          key: ${{ secrets.RSA_PRIVATE_KEY }}
          source: "./module-admin/build/libs/*.jar"
          target: "/home/ec2-user/market-everyone/"
          
      - name: Deploy using ssh
        uses: appleboy/ssh-action@master
        with:
          username: ec2-user
          host: ${{ secrets.HOST }}
          key: ${{ secrets.RSA_PRIVATE_KEY }}
          script_stop: true  # stop script after first failure
          script: nohub java -jar 
